In [50]:
import pandas as pd
import numpy as np


pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 20)

roni_file = "../data/raw/RONI_6-19-2026.xlsx"

mfde_file = "../data/raw/Marine Fisheries Data Explorer Extract - 2026-06-19 11.14.50.xlsx"

roni = pd.read_excel(roni_file)

mfde = pd.read_excel(mfde_file)

In [51]:
roni.head()

   Year  DJF  JFM  FMA  MAM  AMJ  MJJ  JJA  JAS  ASO  SON  OND  NDJ
0  1950 -1.5 -1.3 -1.1 -1.1   -1 -0.7 -0.4 -0.2 -0.2 -0.3 -0.4 -0.6
1  1951 -0.5 -0.2  0.3  0.6  0.6  0.7  0.7  0.8  0.9    1  0.9  0.8
2  1952  0.6  0.4  0.4  0.4  0.3  0.1    0    0  0.1    0    0  0.2
3  1953  0.5  0.8  0.8  0.8  0.8  0.8  0.7  0.7  0.7  0.8  0.8  0.9
4  1954    1  0.7  0.1 -0.2 -0.3 -0.3 -0.5 -0.7 -0.8 -0.7 -0.6 -0.4

In [52]:
roni.info()

<class 'pandas.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    84 non-null     object
 1   DJF     84 non-null     object
 2   JFM     84 non-null     object
 3   FMA     84 non-null     object
 4   MAM     84 non-null     object
 5   AMJ     83 non-null     object
 6   MJJ     83 non-null     object
 7   JJA     83 non-null     object
 8   JAS     83 non-null     object
 9   ASO     83 non-null     object
 10  SON     83 non-null     object
 11  OND     83 non-null     object
 12  NDJ     83 non-null     object
dtypes: object(13)
memory usage: 8.7+ KB

In [53]:
roni.describe()

,Year,DJF,JFM,FMA,MAM,AMJ,MJJ,JJA,JAS,ASO,SON,OND,NDJ
count,84,84,84,84.0,84.0,83.0,83.0,83.0,83.0,83.0,83,83,83
unique,78,37,31,27.0,26.0,24.0,26.0,27.0,31.0,34.0,36,38,37
top,Year,DJF,JFM,-0.3,-0.4,-0.3,-0.3,-0.4,-0.2,-0.2,SON,OND,NDJ
freq,7,7,7,8.0,8.0,8.0,7.0,8.0,7.0,7.0,7,7,7

In [54]:
mfde.head()

   Year Species Group            Species Name        Pounds         Value
0  1980      Rockfish        Rockfish, cowcod         98052         46407
1  1980     Roundfish       Anchovy, northern      94677734       2286978
2  1980        Sharks    Shark, shortfin mako        155327         99270
3  1980         Crabs         Crab, Dungeness      15934778       9597375
4  1980     Roundfish  Lizardfish, California  Confidential  Confidential

In [55]:
mfde.info()

<class 'pandas.DataFrame'>
RangeIndex: 10377 entries, 0 to 10376
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           10377 non-null  int64
 1   Species Group  10377 non-null  str
 2   Species Name   10377 non-null  str
 3   Pounds         10377 non-null  object
 4   Value          10377 non-null  object
dtypes: int64(1), object(2), str(2)
memory usage: 405.5+ KB

In [56]:
mfde.describe()

               Year
count  10377.000000
mean    2003.040956
std       13.099920
min     1980.000000
25%     1992.000000
50%     2003.000000
75%     2014.000000
max     2025.000000

In [57]:
print(roni.columns.tolist())

['Year', 'DJF', 'JFM', 'FMA', 'MAM', 'AMJ', 'MJJ', 'JJA', 'JAS', 'ASO', 'SON', 'OND', 'NDJ']

In [58]:
print(mfde.columns.tolist())

['Year', 'Species Group', 'Species Name', 'Pounds', 'Value']

In [59]:
mfde["Species Name"].nunique()

374

In [60]:
mfde["Species Name"].value_counts().head(20)

Species Name
Anchovy, northern        46
Shark, shortfin mako     46
Crab, Dungeness          46
Sheephead, California    46
Shark, unspecified       46
Octopus, unspecified     46
Sole, Dover              46
Sardine, Pacific         46
Surfperch, redtail       46
Greenling, kelp          46
Rockfish, blackgill      46
Whitefish, ocean         46
Dolphin (fish)           46
Halibut, California      46
Fish, unspecified        46
Skate, unspecified       46
Shark, leopard           46
Bass, giant sea          46
Rockfish, brown          46
Sole, unspecified        46
Name: count, dtype: int64

In [61]:
mfde["Year"].min(), mfde["Year"].max()

(np.int64(1980), np.int64(2025))

In [62]:
mfde.isna().sum()

Year             0
Species Group    0
Species Name     0
Pounds           0
Value            0
dtype: int64

In [63]:
roni.isna().sum()

Year    0
DJF     0
JFM     0
FMA     0
MAM     0
AMJ     1
MJJ     1
JJA     1
JAS     1
ASO     1
SON     1
OND     1
NDJ     1
dtype: int64

In [64]:
mfde.eq("Confidential").sum()

Year                0
Species Group       0
Species Name        0
Pounds           3020
Value            3020
dtype: int64

In [65]:
mfde[mfde.eq("Confidential").any(axis=1)].head(20)

,Year,Species Group,Species Name,Pounds,Value
4,1980,Roundfish,"Lizardfish, California",Confidential,Confidential
12,1980,Roundfish,"Surfperch, pile",Confidential,Confidential
13,1980,Roundfish,"Sardine, Pacific",Confidential,Confidential
15,1980,Bivalves,"Oyster, european flat",Confidential,Confidential
16,1980,Sharks,"Shark, bigeye thresher",Confidential,Confidential
17,1980,Roundfish,"Sculpin, staghorn",Confidential,Confidential
18,1980,Other Snails,"Limpet, unspecified",Confidential,Confidential
20,1980,Rockfish,"Rockfish, blackgill",Confidential,Confidential
24,1980,Rockfish,"Rockfish, copper (whitebelly)",Confidential,Confidential
31,1980,Flatfish,"Halibut, unspecified",Confidential,Confidential
32,1980,Roundfish,Triggerfish,Confidential,Confidential
34,1980,Roundfish,"Surfperch, walleye",Confidential,Confidential
37,1980,Bivalves,"Oyster, giant Pacific",Confidential,Confidential
40,1980,Other Invertebrates,"Worms, marine",Confidential,Confidential
51,1980,Shrimp/prawns,"Shrimp, ghost",Confidential,Confidential
52,1980,Roundfish,"Grunion, California",Confidential,Confidential
57,1980,Roundfish,"Surfperch, calico",Confidential,Confidential
58,1980,Bivalves,"Oyster, eastern",Confidential,Confidential
62,1980,Skates & Rays,"Ray, unspecified",Confidential,Confidential
71,1980,Roundfish,"Bass, striped",Confidential,Confidential

In [66]:
mfde.dtypes

Year              int64
Species Group       str
Species Name        str
Pounds           object
Value            object
dtype: object

In [67]:
mfde["Pounds"] = pd.to_numeric(
    mfde["Pounds"],
    errors="coerce"
)

mfde["Value"] = pd.to_numeric(
    mfde["Value"],
    errors="coerce"
)

In [68]:
mfde.dtypes

Year               int64
Species Group        str
Species Name         str
Pounds           float64
Value            float64
dtype: object

In [69]:
mfde.isna().sum()

Year                0
Species Group       0
Species Name        0
Pounds           3020
Value            3020
dtype: int64

In [70]:
len(mfde)

10377

In [71]:
species_summary = (
    mfde.groupby("Species Name")
    .agg(
        first_year=("Year", "min"),
        last_year=("Year", "max"),
        years=("Year", "nunique"),
        total_pounds=("Pounds", "sum"),
        confidential_years=("Pounds", lambda x: x.isna().sum())
    )
)

species_summary["pct_confidential"] = (
    species_summary["confidential_years"] /
    species_summary["years"] * 100
)

species_summary = species_summary.sort_values(
    "total_pounds",
    ascending=False
)

species_summary.head(25)

,first_year,last_year,years,total_pounds,confidential_years,pct_confidential
Species Name,,,,,,
"Squid, market",1980,2025,46,5.215393e+09,0,0.000000
"Sardine, Pacific",1980,2025,46,1.963841e+09,1,2.173913
"Mackerel, Pacific",1980,2025,46,1.133691e+09,0,0.000000
"Tuna, yellowfin",1980,2025,46,1.092495e+09,0,0.000000
"Tuna, skipjack",1980,2025,46,8.701055e+08,4,8.695652
...,...,...,...,...,...,...
"Herring, Pacific - roe",1993,2018,26,1.029807e+08,8,30.769231
"Rockfish, widow",1980,2025,46,9.898736e+07,0,0.000000
Swordfish,1980,2025,46,7.810757e+07,0,0.000000
"Tuna, bluefin",1980,2025,46,7.780391e+07,0,0.000000
"Sole, petrale",1980,2025,46,6.518316e+07,0,0.000000

In [72]:
species_summary.loc[
    species_summary.index.str.contains("Halibut", case=False)
]

,first_year,last_year,years,total_pounds,confidential_years,pct_confidential
Species Name,,,,,,
"Halibut, California",1980,2025,46,39142719.0,0,0.000000
"Halibut, Pacific",1986,2025,35,196538.0,15,42.857143
"Halibut, unspecified",1980,2022,26,76272.0,10,38.461538

In [73]:
halibut = (
    mfde[mfde["Species Name"] == "Halibut, California"]
    .sort_values("Year")
    .copy()
)

halibut.head()

     Year Species Group         Species Name     Pounds      Value
25   1980      Flatfish  Halibut, California   726550.0  1000982.0
221  1981      Flatfish  Halibut, California  1262018.0  1874168.0
540  1982      Flatfish  Halibut, California  1212312.0  1745829.0
626  1983      Flatfish  Halibut, California  1130363.0  1611535.0
985  1984      Flatfish  Halibut, California  1107019.0  1855602.0

In [74]:
len(halibut)

46

In [75]:
halibut[["Year", "Pounds", "Value"]]

       Year     Pounds      Value
25     1980   726550.0  1000982.0
221    1981  1262018.0  1874168.0
540    1982  1212312.0  1745829.0
626    1983  1130363.0  1611535.0
985    1984  1107019.0  1855602.0
...     ...        ...        ...
9369   2021   778874.0  4228724.0
9510   2022   992108.0  5466920.0
9822   2023   982590.0  5346612.0
9961   2024  1014988.0  5757106.0
10320  2025  1174330.0  6546387.0

[46 rows x 3 columns]

In [76]:
roni.head(15)

    Year  DJF  JFM  FMA  MAM  AMJ  MJJ  JJA  JAS  ASO  SON  OND  NDJ
0   1950 -1.5 -1.3 -1.1 -1.1   -1 -0.7 -0.4 -0.2 -0.2 -0.3 -0.4 -0.6
1   1951 -0.5 -0.2  0.3  0.6  0.6  0.7  0.7  0.8  0.9    1  0.9  0.8
2   1952  0.6  0.4  0.4  0.4  0.3  0.1    0    0  0.1    0    0  0.2
3   1953  0.5  0.8  0.8  0.8  0.8  0.8  0.7  0.7  0.7  0.8  0.8  0.9
4   1954    1  0.7  0.1 -0.2 -0.3 -0.3 -0.5 -0.7 -0.8 -0.7 -0.6 -0.4
5   1955 -0.4 -0.3 -0.3 -0.4 -0.4 -0.4 -0.4 -0.6   -1 -1.4 -1.6 -1.3
6   1956 -0.7 -0.3 -0.2 -0.1    0 -0.1 -0.3 -0.3 -0.3 -0.3 -0.4 -0.2
7   1957    0  0.4  0.7    1  1.1  1.2  1.2  1.3  1.2  1.3  1.5  1.9
8   1958    2  1.9  1.4  1.1  0.8  0.7  0.5  0.3  0.2  0.3  0.4  0.7
9   1959  0.8  0.8  0.7  0.4  0.3 -0.1 -0.2 -0.4 -0.3 -0.3 -0.1    0
10  Year  DJF  JFM  FMA  MAM  AMJ  MJJ  JJA  JAS  ASO  SON  OND  NDJ
11  1960    0    0    0  0.1  0.1    0  0.1  0.2  0.2  0.1    0    0
12  1961  0.1  0.1    0  0.1  0.3  0.3  0.2 -0.1 -0.3 -0.3 -0.2 -0.1
13  1962 -0.1 -0.1 -0.1 -0.2 -0.3 -0.2 -0.1 -0.2 -0.2 -0.4 -0.5 -0.5
14  1963 -0.4 -0.1  0.2  0.2  0.2  0.4  0.7    1    1  1.1  1.2  1.3

In [77]:
roni["Year"] = pd.to_numeric(roni["Year"], errors="coerce")

In [78]:
roni = roni.dropna(subset=["Year"]).copy()

In [79]:
roni["Year"] = roni["Year"].astype(int)

In [80]:
roni.dtypes

Year     int64
DJF     object
JFM     object
FMA     object
MAM     object
AMJ     object
MJJ     object
JJA     object
JAS     object
ASO     object
SON     object
OND     object
NDJ     object
dtype: object

In [81]:
season_cols = roni.columns[1:]

roni[season_cols] = roni[season_cols].apply(pd.to_numeric)

In [82]:
roni.dtypes

Year      int64
DJF     float64
JFM     float64
FMA     float64
MAM     float64
AMJ     float64
MJJ     float64
JJA     float64
JAS     float64
ASO     float64
SON     float64
OND     float64
NDJ     float64
dtype: object

In [83]:
roni = roni[
    (roni["Year"] >= 1950) &
    (roni["Year"] <= 2025)
].copy()

In [84]:
season_cols = roni.columns[1:]

roni["Annual_RONI"] = roni[season_cols].mean(axis=1)

roni_annual = roni[["Year", "Annual_RONI"]]

In [85]:
len(roni)

76

In [86]:
roni["Annual_RONI"] = roni[season_cols].mean(axis=1)

In [87]:
roni_annual = roni[["Year", "Annual_RONI"]]

In [88]:
roni_clean = roni.copy()

In [89]:
halibut = (
    mfde[mfde["Species Name"] == "Halibut, California"]
    .sort_values("Year")
    .copy()
)

halibut = halibut[["Year", "Pounds", "Value"]]

halibut.head()

     Year     Pounds      Value
25   1980   726550.0  1000982.0
221  1981  1262018.0  1874168.0
540  1982  1212312.0  1745829.0
626  1983  1130363.0  1611535.0
985  1984  1107019.0  1855602.0

In [90]:
len(halibut)

46

In [91]:
halibut.describe()

              Year        Pounds         Value
count    46.000000  4.600000e+01  4.600000e+01
mean   2002.500000  8.509287e+05  2.754192e+06
std      13.422618  2.947146e+05  1.141010e+06
min    1980.000000  3.778550e+05  1.000982e+06
25%    1991.250000  5.693525e+05  2.113059e+06
50%    2002.500000  8.903435e+05  2.455798e+06
75%    2013.750000  1.107160e+06  3.081316e+06
max    2025.000000  1.325175e+06  6.546387e+06

In [92]:
roni_annual.head()

   Year  Annual_RONI
0  1950    -0.733333
1  1951     0.550000
2  1952     0.208333
3  1953     0.758333
4  1954    -0.225000

In [93]:
len(roni_annual)

76

In [94]:
halibut_climate = pd.merge(
    halibut,
    roni_annual,
    on="Year",
    how="inner"
)

In [95]:
halibut_climate.head()

   Year     Pounds      Value  Annual_RONI
0  1980   726550.0  1000982.0     0.241667
1  1981  1262018.0  1874168.0    -0.208333
2  1982  1212312.0  1745829.0     1.175000
3  1983  1130363.0  1611535.0     0.475000
4  1984  1107019.0  1855602.0    -0.441667

In [96]:
halibut_climate.info()

<class 'pandas.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Year         46 non-null     int64
 1   Pounds       46 non-null     float64
 2   Value        46 non-null     float64
 3   Annual_RONI  46 non-null     float64
dtypes: float64(3), int64(1)
memory usage: 1.6 KB

In [97]:
halibut_climate.to_csv(
    "../data/processed/halibut_climate.csv",
    index=False
)

In [98]:
roni_annual.to_csv(
    "../data/processed/roni_annual.csv",
    index=False
)

In [99]:
halibut.to_csv(
    "../data/processed/halibut.csv",
    index=False
)